spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
application:
  jwt_secret: gAdmnWaAaOWDiDWag
  access_token_expired: 60 #minute
